export const defaultChannelConfig = {
  // frozen: false,
  // disabled: false,
  // member_count: 2,
  config: {
    created_at: "2023-12-28T19:59:50.427358475Z",
    updated_at: "2023-12-28T19:59:50.427362298Z",
    name: "messaging",
    typing_events: true,
    read_events: true,
    connect_events: true,
    search: true,
    reactions: true,
    replies: true,
    quotes: true,
    mutes: true,
    uploads: true,
    url_enrichment: true,
    custom_events: true,
    push_notifications: true,
    reminders: false,
    mark_messages_pending: false,
    message_retention: "infinite",
    max_message_length: 5000,
    automod: "disabled",
    automod_behavior: "flag",
  },
  own_capabilities: [
    "connect-events",
    // 'create-call',
    // 'delete-channel',
    "delete-own-message",
    // 'flag-message',
    // 'join-call',
    // 'join-channel',
    // 'leave-channel',
    // 'mute-channel',
    // 'pin-message',
    // 'quote-message',
    "read-events",
    // 'search-messages',
    // 'send-custom-events',
    "send-links",
    "send-message",
    "send-reaction",
    // 'send-reply',
    "send-typing-events",
    "typing-events",
    // 'update-channel',
    // 'update-own-message',
    "upload-file",
  ],
  // hidden: false,
};
